services:
  data:
    image: mongo:8.0.19-noble
    container_name: data
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/app/uploads
    # === DEV ONLY: DELETE FOR PROD ===
      - ./server:/app
      - /app/node_modules
    command: npx nodemon -L app.js 
    # =================================
    env_file:
      - ./server/.env
    depends_on:
      - data

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    container_name: client
    ports:
      - "80:80"
    env_file:
      - ./client/.env
    depends_on:
      - server