services:

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/app/uploads
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    container_name: client
    ports:
      - "80:80"
    env_file:
      - ./client/.env
    depends_on:
      - server