services:
  mongodb:
    image: mongo:latest
    container_name: testflow-database
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db

  backend:
    build: ./backend
    container_name: testflow-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
  
  frontend:
    build: ./frontend
    container_name: testflow-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
    environment:
      - CHOKIDAR_USEPOLLING=true
  
    depends_on:
      - backend